# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailHost', models.CharField(max_length=30, verbose_name='SMTP服务器')),
                ('emailPort', models.IntegerField(verbose_name='SMTP端口')),
                ('emailUser', models.EmailField(max_length=100, verbose_name='邮箱帐号')),
                ('emailPassword', models.CharField(max_length=30, verbose_name='邮箱密码')),
            ],
            options={
                'verbose_name': '发件邮箱设置',
                'verbose_name_plural': '发件邮箱设置',
            },
        ),
        migrations.CreateModel(
            name='SystemSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginTitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='登录标题')),
                ('mainTitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='系统标题')),
                ('headTitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='浏览器标题')),
                ('copyright', models.CharField(blank=True, max_length=100, null=True, verbose_name='底部版权信息')),
                ('url', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统URL地址')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
