# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='工单号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.CharField(choices=[('0', '初次安装'), ('1', '售后现场'), ('2', '远程支持'), ('3', '售前支持')], default='0', max_length=10, verbose_name='工单类型')),
                ('status', models.CharField(choices=[('0', '工单已退回'), ('1', '新建-保存'), ('2', '提交-等待审批'), ('3', '已审批-等待执行'), ('4', '已执行-等待确认'), ('5', '工单已完成')], default='0', max_length=10, verbose_name='工单状态')),
                ('do_time', models.DateTimeField(default='', verbose_name='安排时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.CharField(max_length=300, verbose_name='工单内容')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='项目资料')),
            ],
            options={
                'verbose_name': '工单信息',
                'verbose_name_plural': '工单信息',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('0', '退回'), ('1', '派发'), ('2', '执行'), ('3', '确认')], max_length=10, verbose_name='记录类型')),
                ('content', models.CharField(default='', max_length=500, verbose_name='记录内容')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='实施文档')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
            },
        ),
    ]
